Fix compilation errors on Windows
I am seeing compile errors on Windows with clang 12.0.1 such as
```
stderr: node_modules\react-native-svg\windows\RNSVG\PathView.cpp:188:10: error: no member named 'isdigit' in namespace 'std'; did you mean simply 'isdigit'?
  return std::isdigit(static_cast<unsigned char>(c));
         ^~~~~~~~~~~~
         isdigit
C:\open\fbsource\third-party\toolchains\windows10sdk\10.0.18362.0\Include\10.0.18362.0/ucrt\ctype.h:35:56: note: 'isdigit' declared here
_Check_return_ _CRT_JIT_INTRINSIC _ACRTIMP int __cdecl isdigit(_In_ int _C);
                                                       ^
node_modules\react-native-svg\windows\RNSVG\PathView.cpp:192:10: error: no member named 'isupper' in namespace 'std'; did you mean simply 'isupper'?
  return std::isupper(static_cast<unsigned char>(c));
         ^~~~~~~~~~~~
         isupper
C:\open\fbsource\third-party\toolchains\windows10sdk\10.0.18362.0\Include\10.0.18362.0/ucrt\ctype.h:29:56: note: 'isupper' declared here
_Check_return_ _CRT_JIT_INTRINSIC _ACRTIMP int __cdecl isupper(_In_ int _C);
                                                       ^
node_modules\react-native-svg\windows\RNSVG\PathView.cpp:196:10: error: no member named 'isspace' in namespace 'std'; did you mean simply 'isspace'?
  return std::isspace(static_cast<unsigned char>(c));
```

Here we are missing a https://en.cppreference.com/w/cpp/header/cctype import

And
```
third-party\microsoft-fork-of-react-native\public\node_modules\react-native-svg\windows\RNSVG\GroupView.cpp:197:24: error: no viable conversion from 'winrt::RNSVG::implementation::GroupView' to 'winrt::RNSVG::IRenderable'
          renderable = *this;
```
Here we either return or need to static_cast