Fix "more restores than saves" exception
Introduced in PR 2450

java.lang.IllegalStateException: Underflow in restore - more restores than saves
 	at android.graphics.Canvas.restore(Canvas.java:664)
 	at com.horcrux.svg.GroupView.drawGroup(GroupView.java:164)
 	at com.horcrux.svg.GroupView.draw(GroupView.java:88)
 	at com.horcrux.svg.RenderableView.render(RenderableView.java:490)
 	at com.horcrux.svg.GroupView.drawGroup(GroupView.java:132)
 	at com.horcrux.svg.GroupView.draw(GroupView.java:88)
 	at com.horcrux.svg.RenderableView.render(RenderableView.java:490)
 	at com.horcrux.svg.SvgView.drawChildren(SvgView.java:336)
 	at com.horcrux.svg.SvgView.drawOutput(SvgView.java:282)
 	at com.horcrux.svg.SvgView.onDraw(SvgView.java:135)